# -*- coding: utf-8 -*-
#
# Pokémanki Add-on for Anki
# Copyright (C)  2022 zjosua <https://github.com/zjosua>
#
# This file was automatically generated by Anki Add-on Builder v1.0.0-dev.5
# It is subject to the same licensing terms as the rest of the program
# (see the LICENSE file which accompanies this program).
#
# WARNING! All changes made in this file will be lost!

"""
Initializes generated Qt forms/resources
"""

__all__ = [
    "pokemanki_trade",
    "pokemanki_options",
    "pokemanki_egg_exchange",
    "pokemanki_shop"
]

from . import pokemanki_trade
from . import pokemanki_options
from . import pokemanki_egg_exchange
from . import pokemanki_shop